spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/comeet?serverTimezone=UTC # mysql 8.2, mysql workbench 8.0.21 / mac은 8.0.34
    username: comeet
    password: comeet
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 1000
  #    show-sql: true

  jwt:
    header: Authorization
    secret: 394763e7b962d3dbb8367630e7b9e7fa02a5ad01da0387f4f68c0df9f052de83
    access-token-validity-in-seconds : 7200
    refresh-token-validity-in-seconds : 86400

  data:
    redis:
      host: localhost
      port: 6379
    mongodb:
      uri: mongodb+srv://heeyeon807:1234@cluster0.zyob3qk.mongodb.net/comeet?retryWrites=true&w=majority

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ee190e90e2c248f7e25d
            client-secret: b0e3eec509407264d0dcb112d48af219fc98a2e6
          google:
            client-id: 55168987755-ue8uik0qh7lubi6mfkuspatbu0j1390f.apps.googleusercontent.com
            client-secret: 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
          password-salt: A!506@LET3S-SSA%8TAL@

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

logging.level:
  org.hibernate.SQL: debug

aes:
  secret-key: A5d_s3$:Q!EK]e6#Up'HNdK(`?7WhE`L

